import type { Design, ShowcaseItem } from "@/types";

export const designStyles = ["神秘洞穴", "轻盈典雅", "几何艺术", "自然有机", "微型遗迹", "极简现代"] as const;

export const printMaterials = [
  { name: "丝光PLA", desc: "丝缎光泽、低层纹", fit: "轻盈典雅、神秘洞穴" },
  { name: "渐变PLA", desc: "色彩渐变、梦幻层次", fit: "轻盈典雅、极简现代" },
  { name: "哑光PLA", desc: "沉稳厚重、低反光", fit: "神秘洞穴、微型遗迹" },
  { name: "光滑PLA", desc: "高光泽、镜面感", fit: "几何艺术、极简现代" },
  { name: "哑光树脂", desc: "高端精细、薄壁友好", fit: "所有风格展示件" },
  { name: "PA12尼龙", desc: "工业强度、耐用", fit: "大件/承重部件" },
  { name: "仿木PLA", desc: "自然纹理、温润木质", fit: "自然有机、微型遗迹" },
  { name: "半透明树脂", desc: "透光柔和、玻璃感", fit: "极简现代、几何艺术" },
] as const;

export const colorGroups = [
  { name: "莫兰迪灰", colors: [{ name: "灰豆绿", value: "#9baa95" }, { name: "灰蓝", value: "#8d9fac" }, { name: "灰紫", value: "#aaa0b8" }, { name: "灰粉", value: "#c5a4a9" }] },
  { name: "浅色系", colors: [{ name: "象牙白", value: "#f4efe4" }, { name: "奶油白", value: "#f5ead2" }, { name: "浅蓝", value: "#c9dceb" }, { name: "浅绿", value: "#cce2d3" }] },
  { name: "中灰系", colors: [{ name: "青灰", value: "#7f9294" }, { name: "暖泥灰", value: "#9a8f82" }, { name: "冷杉灰", value: "#697774" }, { name: "中灰绿", value: "#718579" }] },
  { name: "深灰系", colors: [{ name: "深炭灰", value: "#343434" }, { name: "磨砂黑", value: "#111111" }, { name: "深空灰", value: "#444a50" }, { name: "深墨绿", value: "#213a32" }] },
  { name: "自然色", colors: [{ name: "抹茶绿", value: "#8da568" }, { name: "雾霾蓝", value: "#88a6b5" }, { name: "松石绿", value: "#3d9d9a" }, { name: "苔藓绿", value: "#5e7446" }] },
  { name: "马卡龙色", colors: [{ name: "薄荷绿", value: "#b9ead7" }, { name: "樱花粉", value: "#f5bccb" }, { name: "奶油黄", value: "#f8dfa0" }, { name: "薰衣草紫", value: "#c9b7e8" }] },
  { name: "高级色", colors: [{ name: "镏金色", value: "#c99a3d" }, { name: "玫瑰金", value: "#b97868" }, { name: "星空银", value: "#c6ccd2" }, { name: "电镀蓝", value: "#3b6fb6" }] },
] as const;

const c = (name: string, value: string) => ({ name, value });

export const designs: Design[] = [
  {
    id: "cave-moon-grotto",
    title: "Moon Grotto",
    description: "一组适合小型鱼群穿行和躲藏的洞穴组合，整体压低视觉重心，让缸体中央留出柔和的水流空间。",
    coverImage: "aqua-cave",
    galleryImages: ["aqua-cave", "aqua-cave-detail", "aqua-cave-top"],
    author: "Finscape Studio",
    authorType: "official",
    isFeatured: true,
    isPublic: true,
    style: "神秘洞穴",
    height: "tall",
    tankSize: { length: 60, width: 30, height: 35 },
    models: [
      { name: "幽灵脸洞", tags: ["穿行", "躲藏"], price: 89, material: "哑光PLA", color: c("深炭灰", "#343434") },
      { name: "多孔洞洞穴", tags: ["穿行", "躲藏"], price: 109, material: "丝光PLA", color: c("灰蓝", "#8d9fac") },
      { name: "悬空桥洞", tags: ["穿行", "悬挂"], price: 119, material: "哑光树脂", color: c("青灰", "#7f9294") },
    ],
    materials: ["哑光PLA", "丝光PLA", "哑光树脂"],
    colors: [c("深炭灰", "#343434"), c("灰蓝", "#8d9fac"), c("青灰", "#7f9294")],
    priceMin: 299,
    priceMax: 459,
    viewCount: 1280,
    createdAt: "2026-05-10",
  },
  {
    id: "minimal-cloud-arch",
    title: "Cloud Arch",
    description: "以留洞雕塑和曲面体块构成的极简现代造景，适合作为桌面缸的主视觉。",
    coverImage: "minimal-cloud",
    galleryImages: ["minimal-cloud", "minimal-cloud-side", "minimal-cloud-material"],
    author: "Finscape Studio",
    authorType: "official",
    isFeatured: true,
    isPublic: true,
    style: "极简现代",
    height: "medium",
    tankSize: { length: 45, width: 28, height: 32 },
    models: [
      { name: "留洞雕塑", tags: ["穿行", "点缀"], price: 108, material: "半透明树脂", color: c("半透明白", "#eaf3f0") },
      { name: "曲面体块", tags: ["点缀", "堆叠"], price: 94, material: "光滑PLA", color: c("象牙白", "#f4efe4"), modelPath: "/models/minimal-modern/curved-surface-block/model.glb" },
      { name: "悬浮块体", tags: ["悬挂", "点缀"], price: 112, material: "渐变PLA", color: c("浅蓝", "#c9dceb") },
    ],
    materials: ["半透明树脂", "光滑PLA", "渐变PLA"],
    colors: [c("半透明白", "#eaf3f0"), c("象牙白", "#f4efe4"), c("浅蓝", "#c9dceb")],
    priceMin: 328,
    priceMax: 528,
    viewCount: 2164,
    createdAt: "2026-05-08",
  },
  {
    id: "organic-forest-root",
    title: "Forest Root",
    description: "自然有机风格的枝条和贝壳洞组合，适合水草密集、层次丰富的生态缸。",
    coverImage: "forest-root",
    galleryImages: ["forest-root", "forest-root-close", "forest-root-layout"],
    author: "AquaDesign",
    authorType: "user",
    isFeatured: true,
    isPublic: true,
    style: "自然有机",
    height: "tall",
    tankSize: { length: 75, width: 35, height: 40 },
    models: [
      { name: "扭曲枝条", tags: ["悬挂", "点缀"], price: 92, material: "仿木PLA", color: c("木纹色", "#9b7653") },
      { name: "贝壳洞", tags: ["躲藏", "穿行"], price: 89, material: "丝光PLA", color: c("苔藓绿", "#5e7446") },
      { name: "菌菇洞", tags: ["躲藏", "堆叠"], price: 96, material: "哑光PLA", color: c("暖泥灰", "#9a8f82") },
    ],
    materials: ["仿木PLA", "丝光PLA", "哑光PLA"],
    colors: [c("木纹色", "#9b7653"), c("苔藓绿", "#5e7446"), c("暖泥灰", "#9a8f82")],
    priceMin: 358,
    priceMax: 620,
    viewCount: 982,
    createdAt: "2026-05-06",
  },
  {
    id: "geo-ripple-tower",
    title: "Ripple Tower",
    description: "几何艺术风格，使用环体拱门和网格塔制造强烈秩序感，适合高透光背景。",
    coverImage: "ripple-tower",
    galleryImages: ["ripple-tower", "ripple-tower-grid", "ripple-tower-color"],
    author: "StoneAqua",
    authorType: "user",
    isFeatured: true,
    isPublic: true,
    style: "几何艺术",
    height: "short",
    tankSize: { length: 60, width: 30, height: 35 },
    models: [
      { name: "环体拱门", tags: ["穿行", "点缀"], price: 98, material: "光滑PLA", color: c("电镀蓝", "#3b6fb6") },
      { name: "波纹墙", tags: ["躲藏", "悬挂"], price: 95, material: "PA12尼龙", color: c("磨砂黑", "#111111") },
      { name: "网格塔", tags: ["堆叠", "躲藏"], price: 105, material: "半透明树脂", color: c("半透明白", "#eaf3f0") },
    ],
    materials: ["光滑PLA", "PA12尼龙", "半透明树脂"],
    colors: [c("电镀蓝", "#3b6fb6"), c("磨砂黑", "#111111"), c("半透明白", "#eaf3f0")],
    priceMin: 388,
    priceMax: 680,
    viewCount: 1508,
    createdAt: "2026-05-04",
  },
  {
    id: "petal-softscape",
    title: "Petal Softscape",
    description: "轻盈典雅的小型组合，适合浅色底砂和低密度水草，整体更柔和亲切。",
    coverImage: "petal-soft",
    galleryImages: ["petal-soft", "petal-soft-palette", "petal-soft-detail"],
    author: "GreenLeaf",
    authorType: "user",
    isFeatured: false,
    isPublic: true,
    style: "轻盈典雅",
    height: "medium",
    tankSize: { length: 40, width: 25, height: 28 },
    models: [
      { name: "圆润曲块", tags: ["点缀", "堆叠"], price: 69, material: "丝光PLA", color: c("奶油白", "#f5ead2") },
      { name: "抽象花瓣形", tags: ["点缀", "悬挂"], price: 88, material: "渐变PLA", color: c("樱花粉", "#f5bccb") },
      { name: "泡泡造型", tags: ["点缀", "躲藏"], price: 76, material: "光滑PLA", color: c("薄荷绿", "#b9ead7") },
    ],
    materials: ["丝光PLA", "渐变PLA", "光滑PLA"],
    colors: [c("奶油白", "#f5ead2"), c("樱花粉", "#f5bccb"), c("薄荷绿", "#b9ead7")],
    priceMin: 249,
    priceMax: 399,
    viewCount: 744,
    createdAt: "2026-05-02",
  },
  {
    id: "ruin-mini-bridge",
    title: "Mini Ruins",
    description: "微型遗迹风格，适合需要故事感的小型造景。断桥、塔尖和石碑形成可探索路径。",
    coverImage: "mini-ruins",
    galleryImages: ["mini-ruins", "mini-ruins-bridge", "mini-ruins-stone"],
    author: "ZenTank",
    authorType: "official",
    isFeatured: false,
    isPublic: true,
    style: "微型遗迹",
    height: "short",
    tankSize: { length: 50, width: 28, height: 32 },
    models: [
      { name: "小型拱门", tags: ["穿行", "点缀"], price: 82, material: "哑光PLA", color: c("深空灰", "#444a50") },
      { name: "塔尖模块", tags: ["堆叠", "点缀"], price: 78, material: "仿木PLA", color: c("木纹色", "#9b7653") },
      { name: "断桥残柱", tags: ["穿行", "堆叠"], price: 104, material: "哑光树脂", color: c("星空银", "#c6ccd2") },
      { name: "石碑遗迹块", tags: ["点缀", "躲藏"], price: 86, material: "哑光PLA", color: c("冷杉灰", "#697774") },
    ],
    materials: ["哑光PLA", "仿木PLA", "哑光树脂"],
    colors: [c("深空灰", "#444a50"), c("木纹色", "#9b7653"), c("星空银", "#c6ccd2"), c("冷杉灰", "#697774")],
    priceMin: 420,
    priceMax: 760,
    viewCount: 601,
    createdAt: "2026-04-28",
  },
  {
    id: "mist-bamboo-valley",
    title: "Mist Valley",
    description: "浅色系的轻盈组合，适合留出大面积游动空间。用圆润曲块和小巧雕塑体块制造雾感层次。",
    coverImage: "petal-soft-detail",
    galleryImages: ["petal-soft-detail", "minimal-cloud-side", "petal-soft-palette"],
    author: "AquaLab",
    authorType: "official",
    isFeatured: false,
    isPublic: true,
    style: "轻盈典雅",
    height: "tall",
    tankSize: { length: 55, width: 30, height: 35 },
    models: [
      { name: "圆润曲块", tags: ["点缀", "堆叠"], price: 69, material: "丝光PLA", color: c("浅绿", "#cce2d3") },
      { name: "小巧雕塑体块", tags: ["点缀"], price: 66, material: "渐变PLA", color: c("浅蓝", "#c9dceb") },
      { name: "泡泡造型", tags: ["点缀", "躲藏"], price: 76, material: "光滑PLA", color: c("奶油白", "#f5ead2") },
    ],
    materials: ["丝光PLA", "渐变PLA", "光滑PLA"],
    colors: [c("浅绿", "#cce2d3"), c("浅蓝", "#c9dceb"), c("奶油白", "#f5ead2")],
    priceMin: 280,
    priceMax: 480,
    viewCount: 536,
    createdAt: "2026-04-24",
  },
  {
    id: "blackwater-shelter",
    title: "Blackwater Shelter",
    description: "为黑水缸和胆小鱼群设计的隐藏空间，洞体更低、更深，整体颜色压暗。",
    coverImage: "aqua-cave-top",
    galleryImages: ["aqua-cave-top", "aqua-cave-detail", "mini-ruins-stone"],
    author: "RiverForm",
    authorType: "user",
    isFeatured: false,
    isPublic: true,
    style: "神秘洞穴",
    height: "medium",
    tankSize: { length: 80, width: 35, height: 40 },
    models: [
      { name: "怪兽洞穴", tags: ["躲藏", "堆叠"], price: 99, material: "哑光PLA", color: c("磨砂黑", "#111111") },
      { name: "表情凹陷", tags: ["点缀", "躲藏"], price: 79, material: "PA12尼龙", color: c("深墨绿", "#213a32") },
      { name: "多孔洞洞穴", tags: ["穿行", "躲藏"], price: 109, material: "哑光树脂", color: c("深空灰", "#444a50") },
    ],
    materials: ["哑光PLA", "PA12尼龙", "哑光树脂"],
    colors: [c("磨砂黑", "#111111"), c("深墨绿", "#213a32"), c("深空灰", "#444a50")],
    priceMin: 360,
    priceMax: 720,
    viewCount: 824,
    createdAt: "2026-04-20",
  },
  {
    id: "coral-frame",
    title: "Coral Frame",
    description: "用珊瑚骨架和环体拱门建立透光框架，适合需要强视觉中心的中大型缸。",
    coverImage: "ripple-tower-color",
    galleryImages: ["ripple-tower-color", "forest-root-close", "ripple-tower-grid"],
    author: "CoralMaster",
    authorType: "official",
    isFeatured: false,
    isPublic: true,
    style: "自然有机",
    height: "short",
    tankSize: { length: 90, width: 45, height: 45 },
    models: [
      { name: "珊瑚骨架", tags: ["穿行", "点缀"], price: 118, material: "半透明树脂", color: c("半透明白", "#eaf3f0") },
      { name: "环体拱门", tags: ["穿行", "点缀"], price: 98, material: "光滑PLA", color: c("电镀蓝", "#3b6fb6") },
      { name: "扭曲枝条", tags: ["悬挂", "点缀"], price: 92, material: "仿木PLA", color: c("木纹色", "#9b7653") },
    ],
    materials: ["半透明树脂", "光滑PLA", "仿木PLA"],
    colors: [c("半透明白", "#eaf3f0"), c("电镀蓝", "#3b6fb6"), c("木纹色", "#9b7653")],
    priceMin: 520,
    priceMax: 920,
    viewCount: 1176,
    createdAt: "2026-04-18",
  },
  {
    id: "quiet-column-study",
    title: "Column Study",
    description: "小型柱阵和曲面体块组成的克制结构，适合喜欢留白和秩序感的玩家。",
    coverImage: "minimal-cloud-material",
    galleryImages: ["minimal-cloud-material", "ripple-tower", "minimal-cloud"],
    author: "Studio North",
    authorType: "user",
    isFeatured: false,
    isPublic: true,
    style: "几何艺术",
    height: "tall",
    tankSize: { length: 50, width: 28, height: 32 },
    models: [
      { name: "柱阵块", tags: ["堆叠", "点缀"], price: 86, material: "光滑PLA", color: c("星空银", "#c6ccd2") },
      { name: "曲面体块", tags: ["点缀", "堆叠"], price: 94, material: "哑光树脂", color: c("象牙白", "#f4efe4"), modelPath: "/models/minimal-modern/curved-surface-block/model.glb" },
      { name: "单体大块", tags: ["躲藏", "堆叠"], price: 88, material: "哑光PLA", color: c("冷杉灰", "#697774") },
    ],
    materials: ["光滑PLA", "哑光树脂", "哑光PLA"],
    colors: [c("星空银", "#c6ccd2"), c("象牙白", "#f4efe4"), c("冷杉灰", "#697774")],
    priceMin: 310,
    priceMax: 560,
    viewCount: 689,
    createdAt: "2026-04-15",
  },
  {
    id: "holiday-lotus-lantern",
    title: "Lotus Lantern",
    description: "节日限定的莲灯造景模板，用半透明件和柔和粉绿配色制造轻微发光感，适合浅色草缸和桌面展示缸。",
    coverImage: "petal-soft-palette",
    galleryImages: ["petal-soft-palette", "minimal-cloud-side", "petal-soft"],
    author: "Finscape Studio",
    authorType: "official",
    isFeatured: true,
    isPublic: true,
    style: "轻盈典雅",
    height: "short",
    tankSize: { length: 45, width: 28, height: 30 },
    models: [
      { name: "莲灯外壳", tags: ["点缀", "躲藏"], price: 96, material: "半透明树脂", color: c("半透明白", "#eaf3f0") },
      { name: "花瓣支架", tags: ["堆叠", "点缀"], price: 82, material: "渐变PLA", color: c("樱花粉", "#f5bccb") },
      { name: "水面小岛", tags: ["点缀"], price: 74, material: "丝光PLA", color: c("浅绿", "#cce2d3") },
    ],
    materials: ["半透明树脂", "渐变PLA", "丝光PLA"],
    colors: [c("半透明白", "#eaf3f0"), c("樱花粉", "#f5bccb"), c("浅绿", "#cce2d3")],
    priceMin: 298,
    priceMax: 520,
    viewCount: 1432,
    createdAt: "2026-05-14",
  },
  {
    id: "designer-moss-canyon",
    title: "Moss Canyon",
    description: "设计师合作款，以峡谷切面和苔藓色块形成深浅层次，适合中型生态缸和虾缸。",
    coverImage: "forest-root-layout",
    galleryImages: ["forest-root-layout", "forest-root-close", "aqua-cave-detail"],
    author: "Mori Lab",
    authorType: "official",
    isFeatured: true,
    isPublic: true,
    style: "自然有机",
    height: "tall",
    tankSize: { length: 60, width: 35, height: 38 },
    models: [
      { name: "峡谷主岩", tags: ["躲藏", "堆叠"], price: 116, material: "哑光PLA", color: c("冷杉灰", "#697774") },
      { name: "苔藓桥片", tags: ["穿行", "悬挂"], price: 88, material: "仿木PLA", color: c("苔藓绿", "#5e7446") },
      { name: "侧边洞穴", tags: ["躲藏", "穿行"], price: 98, material: "哑光树脂", color: c("青灰", "#7f9294") },
    ],
    materials: ["哑光PLA", "仿木PLA", "哑光树脂"],
    colors: [c("冷杉灰", "#697774"), c("苔藓绿", "#5e7446"), c("青灰", "#7f9294")],
    priceMin: 438,
    priceMax: 760,
    viewCount: 1210,
    createdAt: "2026-05-12",
  },
  {
    id: "community-shrimp-hideout",
    title: "Shrimp Hideout",
    description: "社区玩家上传的小型躲藏模板，孔洞密集但体积克制，方便幼虾和小型鱼在前景区域活动。",
    coverImage: "aqua-cave-detail",
    galleryImages: ["aqua-cave-detail", "aqua-cave", "mini-ruins-stone"],
    author: "TankWeekender",
    authorType: "user",
    isFeatured: false,
    isPublic: true,
    style: "神秘洞穴",
    height: "medium",
    tankSize: { length: 35, width: 22, height: 25 },
    models: [
      { name: "蜂巢躲藏块", tags: ["躲藏", "穿行"], price: 72, material: "哑光PLA", color: c("深炭灰", "#343434") },
      { name: "小型拱洞", tags: ["穿行", "点缀"], price: 58, material: "丝光PLA", color: c("灰蓝", "#8d9fac") },
      { name: "前景碎石", tags: ["堆叠", "点缀"], price: 46, material: "PA12尼龙", color: c("暖泥灰", "#9a8f82") },
    ],
    materials: ["哑光PLA", "丝光PLA", "PA12尼龙"],
    colors: [c("深炭灰", "#343434"), c("灰蓝", "#8d9fac"), c("暖泥灰", "#9a8f82")],
    priceMin: 188,
    priceMax: 330,
    viewCount: 492,
    createdAt: "2026-05-11",
  },
  {
    id: "glass-ridge-set",
    title: "Glass Ridge",
    description: "半透明树脂和光滑 PLA 组合的脊线结构，适合需要透光背景和干净秩序感的开放式鱼缸。",
    coverImage: "minimal-cloud-side",
    galleryImages: ["minimal-cloud-side", "minimal-cloud-material", "ripple-tower-color"],
    author: "Studio North",
    authorType: "user",
    isFeatured: false,
    isPublic: true,
    style: "极简现代",
    height: "short",
    tankSize: { length: 70, width: 35, height: 40 },
    models: [
      { name: "透光脊线", tags: ["点缀", "堆叠"], price: 118, material: "半透明树脂", color: c("半透明白", "#eaf3f0") },
      { name: "底部曲面座", tags: ["堆叠"], price: 94, material: "光滑PLA", color: c("象牙白", "#f4efe4") },
      { name: "悬浮小片", tags: ["悬挂", "点缀"], price: 86, material: "渐变PLA", color: c("浅蓝", "#c9dceb") },
    ],
    materials: ["半透明树脂", "光滑PLA", "渐变PLA"],
    colors: [c("半透明白", "#eaf3f0"), c("象牙白", "#f4efe4"), c("浅蓝", "#c9dceb")],
    priceMin: 390,
    priceMax: 690,
    viewCount: 865,
    createdAt: "2026-05-09",
  },
  {
    id: "ancient-gate-run",
    title: "Ancient Gate Run",
    description: "面向长条缸的遗迹路线模板，多个低矮拱门形成连续穿行路径，同时保留后景种植空间。",
    coverImage: "mini-ruins-bridge",
    galleryImages: ["mini-ruins-bridge", "mini-ruins", "mini-ruins-stone"],
    author: "ZenTank",
    authorType: "official",
    isFeatured: false,
    isPublic: true,
    style: "微型遗迹",
    height: "medium",
    tankSize: { length: 90, width: 30, height: 35 },
    models: [
      { name: "连续拱门", tags: ["穿行", "堆叠"], price: 126, material: "哑光树脂", color: c("星空银", "#c6ccd2") },
      { name: "遗迹基座", tags: ["堆叠", "躲藏"], price: 108, material: "哑光PLA", color: c("深空灰", "#444a50") },
      { name: "断裂石板", tags: ["点缀"], price: 72, material: "仿木PLA", color: c("木纹色", "#9b7653") },
    ],
    materials: ["哑光树脂", "哑光PLA", "仿木PLA"],
    colors: [c("星空银", "#c6ccd2"), c("深空灰", "#444a50"), c("木纹色", "#9b7653")],
    priceMin: 460,
    priceMax: 810,
    viewCount: 934,
    createdAt: "2026-05-05",
  },
  {
    id: "electric-reef-loop",
    title: "Electric Reef",
    description: "偏未来感的几何礁石组合，用电镀蓝和半透明件制造视觉中心，适合需要强主题的中大型缸。",
    coverImage: "ripple-tower-grid",
    galleryImages: ["ripple-tower-grid", "ripple-tower-color", "ripple-tower"],
    author: "BlueCurrent",
    authorType: "user",
    isFeatured: false,
    isPublic: true,
    style: "几何艺术",
    height: "tall",
    tankSize: { length: 80, width: 40, height: 45 },
    models: [
      { name: "电镀环礁", tags: ["穿行", "点缀"], price: 132, material: "光滑PLA", color: c("电镀蓝", "#3b6fb6") },
      { name: "透明侧片", tags: ["悬挂", "点缀"], price: 112, material: "半透明树脂", color: c("半透明白", "#eaf3f0") },
      { name: "承重基岩", tags: ["堆叠", "躲藏"], price: 126, material: "PA12尼龙", color: c("磨砂黑", "#111111") },
    ],
    materials: ["光滑PLA", "半透明树脂", "PA12尼龙"],
    colors: [c("电镀蓝", "#3b6fb6"), c("半透明白", "#eaf3f0"), c("磨砂黑", "#111111")],
    priceMin: 560,
    priceMax: 980,
    viewCount: 1048,
    createdAt: "2026-05-03",
  },
];

export const publicDesigns = designs.filter((design) => design.isPublic);
export const featuredDesigns = publicDesigns.filter((design) => design.isFeatured);

export function getDesignById(id: string) {
  return publicDesigns.find((design) => design.id === id);
}

export function getMaterialInfo(name: string) {
  return printMaterials.find((material) => material.name === name);
}

export function toShowcaseItem(design: Design): ShowcaseItem {
  return {
    id: design.id,
    title: design.title,
    style: design.style,
    author: design.author,
    height: design.height,
    priceMin: design.priceMin,
    priceMax: design.priceMax,
    materials: design.materials,
    colors: design.colors,
    modelCount: design.models.length,
    coverImage: design.coverImage,
  };
}
